#!/bin/bash
#
# Helper script for updating the Sphinx documentation. It requires a full install of the
# dependencies so we do that in a mock chroot.
#
# Copyright (C) 2015-2016  Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Brian C. Lane <bcl@redhat.com>
#
MOCKCFG=fedora-rawhide-x86_64

# Pass the script anything to skip re-initializing the chroot
[ -z "$1" ] && mock -r $MOCKCFG --init
mock -r $MOCKCFG -i anaconda-core -i python3-sphinx -i python3-sphinx_rtd_theme -i graphviz
# modules needed to document tests
mock -r $MOCKCFG -i python3-mock -i python3-polib -i python3-pocketlint
mock -r $MOCKCFG --copyin $PWD /builddir/com_redhat_docker/
mock -r $MOCKCFG --chroot "cd /builddir/com_redhat_docker/docs/; make Makefile html"
mock -r $MOCKCFG --copyout /builddir/com_redhat_docker/docs/html $PWD/docs/html.new

echo "Now make sure the ./docs/html.new/ looks ok and copy it over the top of ./docs/html/ and commit."
echo "Then copy ./docs/html/ outside the repo and check out the gh-pages branch. Copy them back to /"
echo "and commit to update the https://rhinstaller.github.io/com_redhat_docker/ page."
